### ISSUE TITLE
aViewer compatibility with Windows 10 / releasing updated versions

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/aviewer#3]
Just a placeholder issue, as Windows 10 final isn't out yet...but worth flagging up that in one of the recent Insider Preview builds (10162) aViewer does not seem to work at all - the application starts, I can register the .dll, but nothing is displayed. In certain situations, I can get the yellow "focus only" rectangle to appear, but even this is inconsistent.

**Comment by ghost** [comment]
Which browser are you using?
Edge browser: Each element doesn't return IAccessible. 
Firefox: The QueryService function for "ISIMPLEDOMNODE" fails. I don't know the cause.
After Windows 10 is released, I will examine them.

**Comment by patrickhlauke** [comment]
Just revisiting this with release version of Windows 10. The aViewer version we currently distribute on the TPG site http://www.paciellogroup.com/resources/aviewer/ crashes consistently as soon as you switch from aViewer (with "highlight focus" and the "show rectangle" options on) to IE11.

The builds here on GitHub do work nicely though. Is there any reason why we're not pointing the public to those builds, rather than the (now outdated, I'm guessing) 2014 version? Could we do a proper "release" and point to it, like we do for WAT? http://www.paciellogroup.com/resources/wat/

**Comment by stevefaulkner** [comment]
@patrickhlauke sounds like something we should do pronto looping in @matatk as he is lord of the releases

**Comment by matatk** [comment]
That sounds like an ominous title :-).  I'm not sure where we are with _this_ aViewer; seems like it is behind the times, as @patrickhlauke says.  The long-term plan would be to:
- Get all the code that makes up CCA, aViewer and WAT into their repos (currently we depend on some binary parts), so that
- we can build a complete release entirely from the source on GitHub (no binaries, on which we currently depend) at any time, and
- we could link the WAT repo to the CCA and aViewer repos, so that when WAT is built, a certain CCA/aViewer release is built (using git submodules would be good for this, as it would allow us to decide which CCA/aViewer revision to include in any given WAT revision, so we can still manage releases).

Steve found what appears to be [a suitable IDE called Lazarus](http://www.lazarus-ide.org) which we are hoping we could use.  Perhaps we could enlist @jun325's help to
- see if lazarus is a viable solution, and, if so,
- get all the code on GitHub so we can start to link things up, as above.

If we could ask @jun325 to get all the source up here and to check the IDE will work for us, then I could look at linking the repos together and making a build process that will build and include them all when WAT is built.  How does that sound?

**Comment by stevefaulkner** [comment]
thanks @matatk sounds like a plan, what can we do in th short term to make the windows 10 compatible version available?

**Comment by patrickhlauke** [comment]
can we just package up the existing `.exe` files that are here right now as a release, and worry about the most correct way to package everything up for the next release? that way, we can get the quick low-hanging fruit of just pointing the TPG site to the github release in the first instance, so in future we won't have to bother updating the site and automagically always point to the freshest version? @matatk

**Comment by matatk** [comment]
Those two approaches are not incompatible -- it would be good to get a release out ASAP, yes.  I think we really need to do the full approach ASAP after that, though, or it'll be a black hole for maintenance time :-).

IIRC there's not much to do to package up an aViewer 'release' as there's no installer, so this could be done quite quickly.  I can look into it later today perhaps... I've made a new issue to track this: #5

**Comment by matatk** [comment]
Also, quick note for future reference: when the above stuff with code has been completed, git should no longer be used to store any .exe or .dll files (as it will not be needed; we will build them).  Only the releases will need to contain such files.

**Comment by patrickhlauke** [comment]
Closing as the immediate issue at the time (Win 10 compat and making a quick release) has been resolved
